### ISSUE TITLE
Improve threads

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#11]
@AlekId
Мое видение..
как ускорить реакцию Куды на печать символов.
можете ли помоч (за плату).

- удаляем опции куды *delayed_parsing*, и всегда реагируем на OnEditorChange (без OnEditorIdle)
- но реагируем по другому. пускаем поток и он парсит **от каретки до конца экрана** (Ed.LineBottom). не весь файл в ННН кб. после этого делаем перерисовку (она покажет все токены на текущем экране).  парсинг одного экрана должен быть быстр наверно.
- потом поток спит 1 сек (не грузить проц при печати) и продолжает парсинг до конца. и потом уже строит fold ranges. и еще одна перерисовка.

**Comment by Alexey-T** [comment]
мой тест показал что парсинг всего 160Кб файла, регулярками ECon, это 50мс. В этом репо положил дему которая пускает парсинг ec_syntanal.pas и показывает 50мс. У вас было 300мс- на один экран- в Куде а не в деме. Наверно меряли с поиском fold ranges (оно медленно)

**Comment by AlekId** [comment]
ммм... не знаю .. Я вообще считаю что проблема не решена. Ваш патч не должен был ничего исправить. Суть в том, что главный поток должен читать, но ничего не писать, в токены и диапазон, как мне кажется.
 А скорость меня пока не интересует -- я хоть и сграбил ваши изменения, все еще испытываю глюки на своей версии исходника. Может, это я перемудрил. Не знаю.

**Comment by AlekId** [comment]
Пока работаю над этим, вот буквально час назад снова начал..

**Comment by AlekId** [comment]
у вас вообще вайн установлен? Какой версии?

**Comment by AlekId** [comment]
На команду
`wine --version`
Должен отвечать
`wine-4.6`
ну или уже 4.7 подоспела..

**Comment by Alexey-T** [comment]
user@PC:~$ wine --version
wine-4.0 (Ubuntu 4.0-1)

надо обновить.

**Comment by AlekId** [comment]
https://wiki.winehq.org/Ubuntu

**Comment by AlekId** [comment]
у вас "стабильная" ветка, древняя, как .. мамонта..

**Comment by AlekId** [comment]
```
sudo dpkg --add-architecture i386 
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
```
далее для 18.04 LTS 
`sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' `
или другие как по ссылке
```
sudo apt update
sudo apt install --install-recommends winehq-devel
```

**Comment by Alexey-T** [comment]
требует libfaudio0. нашел ссылку https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_19.04/ - не знаю что делать.

**Comment by Alexey-T** [comment]
разобрался.

**Comment by Alexey-T** [comment]
user@PC:~$ wine --version
wine-4.7

**Comment by Alexey-T** [comment]
не понимаете почему помогло. Обьекты ecRegExpr создаются внутри SyntaxManager на каждый лексер на каждое правило. потом 2 потока дергают один и тот же лексер. В TecRegExpr.Match() приходят вызовы 2х потоков. и поля FMatchPos, FMatchLen- один поток портит для 2го

**Comment by AlekId** [comment]
но как туда проникают оба потока, одновременно?
 Где-то в адаптере что, дергается метод правила, который вызывает регулярку? Потому что методы клиента я вроде изолировал от одновременного вызова.. Или FMatchPos, FMatchLen используются не для одного вызова, а как-бы хранят состояние?

**Comment by Alexey-T** [comment]
FMatchPos, FMatchLen это поля класса TecRegexpr. объект на каждое правило лексера. напр, на "число в Питоне". тогда 2 потока дошли до числа в питоне и оба заходят в метод и портят поля

**Comment by AlekId** [comment]
но они не должны туда попадать одновременно! Давайте, проверим.
Вместо Enter используйте TryEnter и 
```
ready:= sect.TryEnter;
if not ready then 
ready := false
else sect.Enter;
```
и поставьте бряк на предпоследнюю строчку, посмотрите по стеку вызовов, откуда он идет

**Comment by AlekId** [comment]
```
ready:= sect.TryEnter;
if not ready then begin
ready := false//сюда бряк
 sect.Enter;
end;
```

**Comment by Alexey-T** [comment]
отсюда
```
#0 MATCH(0x7ffff447c120, 0x7ffff0649068 '{'#10' /', '*' <repeats 21 times>..., 3617, false) at ec_regexpr.pas:1952
#1 MATCHLENGTH(0x7ffff447c120, 0x7ffff0649068 '{'#10' /', '*' <repeats 21 times>..., 3617, false) at ec_regexpr.pas:1991
#2 MATCH(0x7ffff4486240, 0x7ffff0649068 '{'#10' /', '*' <repeats 21 times>..., 3617) at ec_syntanal.pas:2444
#3 GETTOKEN(0x7ffff4514c40, 0x7ffff4a2af20, 0x7ffff0649068 '{'#10' /', '*' <repeats 21 times>..., 3617, false) at ec_syntanal.pas:4610
#4 EXTRACTTAG(0x7ffff4a2af20, 0x7ffff0649068 '{'#10' /', '*' <repeats 21 times>..., 3617) at ec_syntanal.pas:2950
#5 DOSYNTAXWORK(0x7ffff4a2af20) at ec_syntanal.pas:3430
#6 DOAPPENDTOPOS(0x7ffff4a2af20) at ec_syntanal.pas:3538
#7 EXECUTETASK(0x7ffff0fb0680, {TASK = {Proc = {function  (POINTER) : BOOLEAN} 0x7ffff06479d0, Self = 0x7ffff4a2af20}, DONEHANDLER = {Proc = {procedure (POINTER, TOBJECT)} 0x7ffff06479d0, Self = 0x7ffff4a2af20}, ARG = 0, EXPENDABLE = true}) at ec_async.pas:442
#8 EXECUTE(0x7ffff0fb0680) at ec_async.pas:423
#9 CLASSES_$$_THREADFUNC$POINTER$$INT64 at :0
#10 ?? at :0
#11 ?? at :0
#12 ?? at :0
#13 SYSTEM_$$_SYSFREEMEM_FIXED$PFREELISTS$PMEMCHUNK_FIXED$$QWORD at :0
#14 ?? at :0
#15 ?? at :0
```

**Comment by Alexey-T** [comment]
```
function TecRegExpr.Match(const InputString: UCString; var aPos: integer; Back: Boolean): Boolean;
var
  r: longint;
begin
  //EnterCriticalSection(FCriSection);
  r:= TryEnterCriticalSection(FCriSection);
  if r=0 then
  begin
     r:= 0;
     EnterCriticalSection(FCriSection);
  end;

```

**Comment by AlekId** [comment]
ага, но нам нужен главный поток. Там в лазаре есть View->Debug Windows->Threads 
там несколько потоков, и кнока Select выбирайте последовательно, пока в стеке вызовов не будет виден метод адаптера.

**Comment by AlekId** [comment]
не Select а Current

**Comment by Alexey-T** [comment]
![Screenshot from 2019-05-01 17-02-34](https://user-images.githubusercontent.com/4154978/57020944-932f6700-6c33-11e9-8a4e-8b8ef3a20e40.png)

**Comment by Alexey-T** [comment]
![Screenshot from 2019-05-01 17-03-31](https://user-images.githubusercontent.com/4154978/57020987-b4905300-6c33-11e9-93a3-55f1560bd157.png)

**Comment by Alexey-T** [comment]
точнее там не те поля, а одно поле FMatchOK.

**Comment by Alexey-T** [comment]
точнее больше полей.
  TreSubExpr = class(TreListNodeBase)
  private
    FStart: integer; // first char of sub expression
    FEnd: integer; // first char after sub expression

**Comment by AlekId** [comment]
вы показываете 6 поток, а главный кажется, номер 7 -- вот его выделить, и нажать Current, посмотреть, что в стеке вызовов.

**Comment by AlekId** [comment]
6- поток это синтаксер, у него легитимный доступ к токенам, регексу, по моей крит. секции FSyncWall..

**Comment by Alexey-T** [comment]
![2](https://user-images.githubusercontent.com/4154978/57021442-e524bc80-6c34-11e9-94cc-bebabc0c2d9c.png)

**Comment by AlekId** [comment]
опять не то, теперь главный, скорее всего 6 -- вы же по стеку вызовов видите -- если идет от файла ec_asyc, из метода Execute, то это синтаксер, а главный поток пойдет по стеку из методов адаптера

**Comment by Alexey-T** [comment]
та же сессия, поток 6 и 7 оба идут от  ec_async.
![3](https://user-images.githubusercontent.com/4154978/57021682-975c8400-6c35-11e9-86c4-e69eaccb72d9.png)

**Comment by Alexey-T** [comment]
вот поток 1 главный
![4](https://user-images.githubusercontent.com/4154978/57021732-bf4be780-6c35-11e9-9f5c-4535fa24a76b.png)

**Comment by Alexey-T** [comment]
конфликт потока 6 и 7 - это 2 открытых вкладки в 2 групах.

**Comment by AlekId** [comment]
вот это да..  Я ограждал синтаксер от главного потока, но не думал, что что два синтаксера могут иметь одни и те же ресурсы..  Думал, что все данные в клиентах, а клиенты изолированы. 
Этот регекс ведь не клиенту принадлежит? А лексеру? Верно?

**Comment by Alexey-T** [comment]
верно. Лексеру. А лексер принаджедит SyntaxManager. он общий на все вкладки

**Comment by AlekId** [comment]
по хорошему, нужно тогда проводить ревизию всех классов правил (TRuleCollectionItem), чтобы убедиться, что данные (поля) правил либо неизменяемы, после чтения грамматики, либо потокобезопасны.

**Comment by Alexey-T** [comment]
AFAIK они только чтение, после чтения лексеров из файлов. 

меняются только эти при смене "темы"- TecStylesCollection

**Comment by AlekId** [comment]
ну вот регекс как раз меняется, в своих внутренних полях.. Если одно и то же правило чекается в разных потоках, то получаем что попало..

**Comment by Alexey-T** [comment]
Regex потоко небезопасен,  это обошёл..

**Comment by AlekId** [comment]
любое изменяемое поле непотокобезопасно, если только не ограждено синхронизацией, да  и то без гарантии.

**Comment by Alexey-T** [comment]
подумаю, можно ли переделать regex (поля -> лок.перемен.)

**Comment by Alexey-T** [comment]
записал тему в #12 ... это закроем.
