### ISSUE TITLE
Threads: react fast to text input

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#12]
как ускорить реакцию Куды на печать символов.

 -   удаляем опции куды delayed_parsing, и всегда реагируем на OnEditorChange (без OnEditorIdle)
 -   но реагируем по другому. пускаем поток и он парсит от каретки до конца экрана (Ed.LineBottom). не весь файл в ННН кб. после этого делаем перерисовку (она покажет все токены на текущем экране). парсинг одного экрана должен быть быстр наверно.
-    потом поток спит 1 сек (не грузить проц при печати) и продолжает парсинг до конца. и потом уже строит fold ranges. и еще одна перерисовка.

**Comment by AlekId** [comment]
не поможет. Так сейчас и работает примерно, за исключением секундной паузы после AppendToPos.
нужно парсить только одну строку, сохраняя всё, что до, и всё что после..

**Comment by Alexey-T** [comment]
multiline comments до конца файла.
