### ISSUE TITLE
threads: issues

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#15]
https://github.com/Alexey-T/EControl/commit/2a1fd4e11dda6a24e8d05c26c8808ce8c202c11c

добавил блокировку для метода CompileGrammer другого класа (там дергаются методы парсера, напр. TagStr[]). @AlekId

**Comment by Alexey-T** [comment]
```
procedure TecClientSyntAnalyzer.CloseAtEnd(StartTagIdx: integer);
begin
  AssertCoherent();
```
почему вы тут не сделали блокировку такую же WaitTillCoherent? @AlekId

**Comment by Alexey-T** [comment]
блокировка там нужна- неявно она была в TagStr[].
Теперь TagStr всегда идет внутри блокировки
(проверил все места). тогда давайте удалим блокировку внутри  TagStr? @AlekId

**Comment by AlekId** [comment]
> почему вы тут не сделали блокировку такую же WaitTillCoherent? @AlekId
там не должно быть асинхронного вызова. Грамматики парсятся без асинхрона.

**Comment by AlekId** [comment]
мне кажется в адаптере проблема. Если стартует программа, и потом открывает старый сеанс, то AppendToPos вызывается для начала файла, а потом уж перемещается каретка ввода, скажем, в середину -- на более дальнюю, неспарсенную позицию

**Comment by Alexey-T** [comment]
Да, и юзер видит некрашеный текст, пока не допарсит до экрана - так и было

**Comment by AlekId** [comment]
это исправлено уже?

**Comment by Alexey-T** [comment]
Нет, Это всегда так было

**Comment by AlekId** [comment]
так сейчас еще хуже -- экран остается некрашенным до того, как вообще всё не спарсится, до конца файла. Это нужно исправить, разве нет? Где вообще это происходит?

**Comment by AlekId** [comment]
установка позиции в Synedit?

**Comment by Alexey-T** [comment]
не дома. Попробую дома передать в on progress номер текущей строки и от него делать update

**Comment by Alexey-T** [comment]
Попробую когда дома, дать в  OnLexerProgress больше инфо и по ней делать рисовку если дошли до экрана

**Comment by Alexey-T** [comment]
Отформатировал часть вашего кода руками, сделайте pull

**Comment by AlekId** [comment]
вам не кажется, что в TecSyntAnalyzer.GetToken происходит утечка памяти?
result инициализируется дважды..

**Comment by AlekId** [comment]
а насчет пулла.. у меня форкнутая версия сильно отличается от вашей -- посмотрите сами.

**Comment by AlekId** [comment]
код нужно причесывать, когда уже всё готово, да и не в форматировании дело..

**Comment by AlekId** [comment]
и нужно всерьез подумать над оптимизацией регекса.. Он слишком медленный, как думается.

**Comment by AlekId** [comment]
да, я не посмотрел, что токен является записью

**Comment by Alexey-T** [comment]
- format src: руки чесались. Еще поформаттил. пробелы и инденты. в паре мест ввел константы. убрал константу отсюда- //const minTokenStep = 0;

- надо оптимайзить regex- уверены? Добавил демку в репо ECon. она прогоняет 160K файл Н правилами за 50мс

**Comment by Alexey-T** [comment]
- на питон-файле видел assert (Buffer.Setup), но иногда! когда коментил по Ctrl+/ строки.
поправил его так- криво но пашет- 
https://github.com/Alexey-T/ATSynEdit_Ex/commit/1f571c1b72fd3c0611870aedad2b3e8c557e728a

**Comment by AlekId** [comment]
а тот файл _big.pas с паскалем, за скока прогоняет.
ассерт был потому, что changeAtPos лочил буфер, хотя ему это было без надобности. В новой версии это исправлено -- я уже добавил новые баги.

**Comment by Alexey-T** [comment]
улучшил демо- можете выбрать там кнопой любой pas file.
1.5M pas file -- 960ms.
