### ISSUE TITLE
Last thread fixes

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#17]
могу влить ваши патчи - но может пока без "раздербанил" или его тоже надо?
до него 2 патча.
хочу сохранить форматирование (вливать руками).
и обновить весь ec_async. делать? @Alekid

**Comment by Alexey-T** [comment]
"раздербанил" дергает ec_syntgrammer на к файлов- не стОит imho, было понятнее что относится к граммару а что нет.

**Comment by AlekId** [comment]
слушайте, тема такая -- я почти уверен, что это где-то адаптер косячит. 

Синтаксер и клиент дают ему нормальные данные, но он тупо недокрашивает..
[cudatext.zip](https://github.com/Alexey-T/EControl/files/3143890/cudatext.zip)
я собрал вот текущую версию, и она недокрашивает, порой 1-2 токена, рандомно, после AppendToPos. На _big.pas
Причем после полного парсинга, повторное окрашивание решает проблему -- именно потому думаю, что дело  не в битых данных клиента -- иначе бы повторное окрашивание не дало бы другого результата.

**Comment by Alexey-T** [comment]
посмотрю эту тему.
а патчи к econtrol- можете принять мои патчи #18 чтобы я потом взял ваши файлы?

**Comment by Alexey-T** [comment]
посмотрю эту тему.
Взял все ваши пачи (пропало мое форматирование).
поправил под них Куду, synedit, synedit_ex.
