### ISSUE TITLE
thread: File/Reopen works bad

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#20]
на большом .pas file: Cudatext File/Reopen работает плохо

- нет прогресса парсинга 
- работаает в 3-4 раза дольше, ждал 15 сек (раньше было 5)
@AlekId

**Comment by Alexey-T** [comment]
(мое репо EC почти равно вашему)

**Comment by AlekId** [comment]
это полный парсинг 15 сек? Я воткнул ожидаение в 1 секунду в DoSyntaxWork, как вы предлагали. Вы тестировали на своём билде, без лога?
Так еще привязан AppendToPos к адаптеру, к событию подстветки -- таким образом можно решить проблему открытия неокрашивания..

**Comment by Alexey-T** [comment]
полный, и даже не 15 а вообще не закончится (после File/Reopen).
я тестил с вашим EControl но с моим adapter.

**Comment by Alexey-T** [comment]
давайте дам Discord чат, постучите на support (@) uvviewsoft.com

**Comment by AlekId** [comment]
и как этим пользоваться? То вам телеграм, который сходу просит номер телефона, то блин _это_, -- я этим не пользовался никогда

**Comment by Alexey-T** [comment]
это чат на Электроне, с голосовыми звонками, на десктопе.

**Comment by AlekId** [comment]
> чат на Электроне
предполагается, я пойму с полуслова? Не то поколение.. Я закончил играть раньше, чем появился интернет..

**Comment by Alexey-T** [comment]
Программа чата - на движке Electron (Хром), т.е. тяжелая и удобная.
https://discordapp.com/
скриншот
https://i.imgur.com/lIcKa30.jpg

**Comment by AlekId** [comment]
Я не стану пользоваться голосовым чатом.
Вернемся к теме.  Я посмотрю, что в вашей ветке адаптера.

**Comment by Alexey-T** [comment]
ОК, можно без голосовых вызовов, просто иметь там текстовый чат (с аттачами до 8М)

**Comment by AlekId** [comment]
я скачал приложение. Но я не понимаю, как им пользоваться. Нужно присоединиться к серверу? Тогда к какому? Или что?

**Comment by Alexey-T** [comment]
запускаете, в левой полосе кнопок хмете большой + , и там join to server. вводите URL сервера, дам его по емейлу. вы соединитесь с моим сервером. и там в списке буду я, Alextp. кликаете на мое имя, будет чат. и я могу начать чат.

**Comment by AlekId** [comment]
хм.. так что, повторюсь, от меня требуется? Конкретно?

Я не увидел в коде вашего адаптера чтобы вы добавили что-то существенное. 
ATSynEdit_fgl не принадлежала пакету ATSynEdit. Пулл реквест

**Comment by Alexey-T** [comment]
Пулл сейчас приму. меня коробит такое форматирование но приму

**Comment by AlekId** [comment]
а что не так с форматированием?

**Comment by Alexey-T** [comment]
я привык ставить пробел после `,` и `:` и `:=` но не до. (В ECon стоит и после и до `:=`.)

**Comment by Alexey-T** [comment]
Discord отложим, если трудно

**Comment by AlekId** [comment]
лишние пустые строки? Ерунда! вот кода переменные однобуквенные, невразумительные -- это криминал.. 
Я кажется решил, пусть и совсем корректно, проблему недокраски -- надо было вызывать UpdateEditors, я чтобы очистить кэш окраски в самом SynEdit, а не только в адаптере.
Теперь вроде красит. Причем красит даже после скролла -- любая попытка скролла вызывает динамическую окраску(хотя бы на данном лексере), и тут-же вызывает AppendToPos, который вытесняет другие задачи(кроме ChangedAtPos) и работает + 30 строк от нижней границы экрана
по завершении AppendAtPos заставляет Synedit перекраситься.

**Comment by AlekId** [comment]
а что до форматирования -- ну а что, встроенный в лазарь авто-форматтер не справляется ?

**Comment by Alexey-T** [comment]
форматирование- пока не пробовал Laz fmt, не знаю может ли он форматить выделенные блоки.

правка-
интересно. " любая попытка скролла вызывает динамическую окраску"- а если файл уже распарсен? а если скаролл идет в середине огромного файла который только начал парситься?

**Comment by AlekId** [comment]
> любая попытка скролла вызывает динамическую окраску"- а если файл уже распарсен
ну вроде оно повторно парситься не будет

> любая попытка скролла вызывает динамическую окраску"- а если файл уже распарсен
ага, AppentoPos будет работать до этой середины, и вызовет перекраску, как только доберется
это проблема производительности, которую предстоит решить.

**Comment by Alexey-T** [comment]
Ок, хорошо

**Comment by AlekId** [comment]
но вообще это не очень хорошо. Почему-то этот ваш адаптер не реагирует на скролл /прокрутку. Её нужно обрабатывать, а не динамический хайлайт
И почему, когда CudaEdit открывает сессию, она не скроллит на прежнюю позицию -- это я что-то испортил, или уже было?
А динамическая подстветка -- что она делает ?

**Comment by Alexey-T** [comment]
А зачем обрабатывать прокрутку?

Dynamic highlight это подтветка токенов другим цветом в зависим от позиции каретки.  Юзается Паскаль лексом когда каретка внутри begin..end- эти два слова подсветятся

**Comment by Alexey-T** [comment]
В сессии сохраняется index of top line или просто каретка, должна восстанавливать ее

**Comment by AlekId** [comment]
> В сессии сохраняется index of top line или просто каретка, должна восстанавливать ее
да, я это видел. Позиция каретки сохраняется, но не сохраняется экран. Открывается в начале, а каретка может быть в середине файла. Если нажать стрелку, то редактор дернет вид на позицию  каретки. 
То есть после LineTop нужно еще вызывать что-то вроде ScrollToCaret

> А зачем обрабатывать прокрутку?
перекраска вызывается дважды -- после AppendToPos, который призван закрасить текущий видимый экран, и после DoSyntaxWork, который распарсивает остальное, последующее.
Нам нужно, чтобы если юзер прокручивал экран, то вызывался бы AppendToPos с соответсвующей позицией, до которой нужно раскрасить как можно быстрее.

**Comment by Alexey-T** [comment]
Вспомнил.. экран тоже восстановится но после onParseDone, иначе было не сделать..

**Comment by Alexey-T** [comment]
Надо добавить в адаптер событие ObEditorScroll?

**Comment by AlekId** [comment]
да, думаю так.

**Comment by Alexey-T** [comment]
Todo

**Comment by Alexey-T** [comment]
уже было OnEditorScroll в адаптере (базовом, но не в adapter_econtrol).
```
procedure TATSynEdit.DoEventScroll;
begin
  if Assigned(FAdapterHilite) then
    FAdapterHilite.OnEditorScroll(Self);

  if Assigned(FOnScroll) then
    FOnScroll(Self);
end;
```

**Comment by AlekId** [comment]
![output](https://user-images.githubusercontent.com/11839048/57181653-ee14c880-6e96-11e9-886c-b629ddcafbc1.png)

**Comment by Alexey-T** [comment]
Profiler какой то? Что это

**Comment by AlekId** [comment]
gprof, это открытие и парсинг _big.pas

**Comment by AlekId** [comment]
на 64-битах не работает. На вин запусить трудновато, хотя, наверное, возможно.

**Comment by AlekId** [comment]
в основном нагрузка на лексер, проверка условий, я сейчас пытаюсь ушить узкие места.

**Comment by AlekId** [comment]
или расшить, правильнее сказать

**Comment by Alexey-T** [comment]
ЗдОрово..

**Comment by Alexey-T** [comment]
посмотрел отчет. Есть мысли. Там поиск "блоков" делается из ExtractTag- это метод SelectTokenFormat. надо б отложить поиск блоков на позже...

**Comment by Alexey-T** [comment]
лучше б доделать что есть сейчас- а это оптимизировать потом.

**Comment by AlekId** [comment]
у вас при закрытии приложения не останавливаются таймеры. Сделайте так, чтобы _все_ таймеры были остановлены в FormCloseQuery

**Comment by AlekId** [comment]
```
procedure TfmMain.StopTimers;
begin
  TimerAppIdle.Enabled:=false;
  TimerCmd.Enabled:=false;
  TimerEdCaret.Enabled:=false;
  TimerStatusBusy.Enabled:=false;
  TimerStatusAlt.Enabled:=false;
  TimerStatus.Enabled:=false;
  TimerTreeFill.Enable:=false;
end;
```

**Comment by Alexey-T** [comment]
сделал, пач по ссылке.

**Comment by Alexey-T** [comment]
main.pp, File/Realod - парсит больше 30с, на 2 третях остановилось.

**Comment by AlekId** [comment]
у вас неактуальный исходник, я многое изменил.

**Comment by Alexey-T** [comment]
Рад слышать..

**Comment by Alexey-T** [comment]
Хочу взять пачи atsynedit_ex, мешает вот это
https://github.com/Alexey-T/ATSynEdit_Ex/issues/5

**Comment by Alexey-T** [comment]
Записал себе https://github.com/Alexey-T/CudaText/issues/2002

**Comment by Alexey-T** [comment]
Хм- вообще-то у меня работает- при восст. сессии с main.pp  в середине Куда скроллит к середине. у меня Лин64. Т.е. это работало в 1.79.2, с старым кодом )

**Comment by Alexey-T** [comment]
https://github.com/Alexey-T/EControl/issues/22
надо поправить для компиляции.

**Comment by Alexey-T** [comment]
Посмотрите руборд, личку, плс.

**Comment by AlekId** [comment]
верните всё как было. У вас берется без проверки индекса.

**Comment by Alexey-T** [comment]
вернул. Теперь не компилируется. зайдете в чат? я там уже написал. Там можно это говорить

**Comment by AlekId** [comment]
пулл сделали с ATSynedit?

**Comment by Alexey-T** [comment]
да.
