### ISSUE TITLE
About current EC code

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#5]
@AlekId 
EControl- как оно работает счас.
у EC, у его класса ecClientSyntAnalizer, юзаются два главных метода.
AppendToPos - парсить до нужной позиции - без таймера, просто.
IdleAppend - парсить таймером, видимо до конца.

в "адаптере" ATSynedit_Ex видно это:
atsynedit_adapter_econtrol.pas
```
procedure TATAdapterEControl.DoAnalize(AEdit: TATSynEdit; AForceAnalizeAll: boolean);
  if AForceAnalizeAll then
  begin
    // этот блок вызывается плагинами через апи- тут без таймера
    AnClient.TextChanged(0);
    AnClient.Analyze;
    AnClient.IdleAppend;
  end
  else
  begin
    // это вызывается едитором при правках - простой парсинг 
    // до нижней строки экрана LineBottom. потом уже таймером до конца.
    NLine:= AEdit.LineBottom;
    if NLine=0 then
      NLine:= AEdit.GetVisibleLines;
    NLine:= Min(NLine, Buffer.Count-1);
    NPos:= Buffer.CaretToStr(Point(0, NLine));
    AnClient.AppendToPos(NPos);
    AnClient.IdleAppend;
  end;
```

**Comment by Alexey-T** [comment]
что делает парсинг EC.
он очищает список токенов FTagList начиная от позиции последней правки. и потом анализирует буфер FBuffer.Text (весь текст файла в одной строке) добавляя токены в FTagList.

потоки - должны будут делать свой обьект TempTagList и анализировать токены в него.
а при окончании парсинга (и видимо при парсинге до конца текущего экрана тоже) сбрасывать накопленные токены в FTagList (и обновлять редактор который прочтет FTagList).

**Comment by AlekId** [comment]
я пока разбираюсь. Инфраструктура потока и логика тасков вчерне сделана, но нужно очень аккуратно согласованность данных проверять
полагаю нужно не только делать рабочую копию FTagList, но и как-то защитить FSubLexerBlocks
А IdleAppend эта та еще песня..
![CalledBy-IdleAppend](https://user-images.githubusercontent.com/11839048/56466873-d3167300-6417-11e9-88c2-74e39fc59e37.png)

**Comment by AlekId** [comment]
![ObjectRefswithCalledBy-FSubLexerBlocks](https://user-images.githubusercontent.com/11839048/56466968-4d93c280-6419-11e9-87ca-08e116c8dd51.png)

**Comment by Alexey-T** [comment]
Не то что защитить а сделать свою копию в потоке. это делать для- FSubLexerBlocks, FRanges (folding ranges), FOpenedBlocks (те же ranges но незакрытые)

**Comment by AlekId** [comment]
пока пробую защитить, иначе придется копировать -- реально может быть тяжелой по нагрузке задачей.  Потом, если копировать, то где? В главном потоке? Шило на мыло, в рабочем? Опять таки защищать

**Comment by Alexey-T** [comment]
копировать объекты как? так легко - надо копировать TempTagList -> FTagList так

//enter critical sec
Tmp:= FTagList;
FTagList:= TempTagList;
Tmp.Free;
TempTagList:= nil;
//end critical

не поэлементно

**Comment by AlekId** [comment]
так рабочий поток их меняет, добавляет, удаляет насколько я понял. 
FTagList:= TempTagList; 
это даже не shallow copy а тупо копирование указателя. Это ничего не даст. Tmp.Free; учитожит и FTagList.
Но это не суть. Как копировать FTagList я уже знаю, и это сделал.
С другими структурами тоже разберусь
Вопрос в другом -- как переключить поток в отладчике лазаря? У меня сейчас деадлок, где-то я не додумал. Так теперь еще не вижу по стеку вызовов, что кого ждет.

**Comment by Alexey-T** [comment]
даже не знаю. гугл не говорит. нашел вот- http://wiki.freepascal.org/Multithreaded_Application_Tutorial

**Comment by AlekId** [comment]
я такой же умный как вы. Проблема в том что даже тупо текстовую команду gdb послать нет возможности. Типо в Лазаре всё гуёвое, только с другой буквы начинается.

**Comment by Alexey-T** [comment]
можно делать writeln и пускать прогу из консоли Лин чтобы видеть вывод.

**Comment by AlekId** [comment]
я уже прикрутил логгер из mormot. Да и проблема решилась

**Comment by Alexey-T** [comment]
не пробовал Mormot, не знаю.

**Comment by AlekId** [comment]
![screenshot 2019-04-21 001](https://user-images.githubusercontent.com/11839048/56471465-2d80f500-6453-11e9-8514-b33b18dc2115.png)

**Comment by Alexey-T** [comment]
Значит лог по http и вьюер есть.

**Comment by AlekId** [comment]
ага, и стек вызовов

**Comment by AlekId** [comment]
только тянет за собой зависимость от FPC транк, на стабильном FPC не собирается. там модуль SynCommons типичное спагетти.

**Comment by Alexey-T** [comment]
Думаю надо создавать поток при первом Парсинге (пока парсинг не начался в фоновой вкладке, потока нет). И поток лучше бы висел пассивно после конца парсинга- 10 секунд, по свойству- а потом (при неактивности, вкладка стала фоновой) убивался

**Comment by Alexey-T** [comment]
есть какой-то прогресс?

**Comment by AlekId** [comment]
[del.zip](https://github.com/Alexey-T/EControl/files/3117940/del.zip)
да, я вчерне закончил. От копирования тегов отказался в итоге -- это только замедлит приложения. Расставил на внешне видимые методы клиента критические секции (acquireSync) AppendToPos, TimerIdleTick в рабочем потоке. ChangeAtPos -- не стал, не вижу профита.  Мелкие изменения в адаптере. 
Рабочий поток не создается для парсинга грамматик (в конструкторе клиента параметр есть булевый). Немного поправил чтение грамматик -- слишком часто вызывался CompileGrammar, и дергался парсинг.

**Comment by AlekId** [comment]
код потока в отдельном файле. Инфраструктура для копирования тегов, если всё же понадобится, есть.

**Comment by AlekId** [comment]
в принципе, рабочий поток может приостанавливаться -- я предусмотрел это, давая доступ главному потоку к тегам и  и диапазонам, только что-то не особенно они этим пользуются. 
Не совсем правда понятно, насколько согласованы данные , скажем, в середине AppentoPos или TimerIdleTick

**Comment by AlekId** [comment]
ну и под линью нужно посмотреть, что творится

**Comment by Alexey-T** [comment]
пока взял .ехе, он работает. тестю на виртуалке (мало ли вирус). и там редактирование python file тормозит - может из-за лога...
потом когда допишется, хочу потестить (насколько пропали паузы из-за таймера).

**Comment by AlekId** [comment]
дайте файл который тормозит

**Comment by AlekId** [comment]
я только с паскалевским парсером проверял.

**Comment by Alexey-T** [comment]
вопрос...
В Куде есть опция
lexer_delayed_parsing_size
If text size is bigger than this option, lexer analysis becomes delayed,
ie only after last text change + pause (during this pause you'll see non-colored text)

Она работает для больших файлов, пускает парсинг по idle после посл.правки.
С потоком ее можно будет удалить?
теперь же неважно большой файл или нет- паузы для юзера не будет?

**Comment by Alexey-T** [comment]
питон файл - https://github.com/kvichans/cuda_find_in_files/blob/master/cd_fi_in_fi.py

**Comment by AlekId** [comment]
эта опция
```
UiOps.LexerDelayedParsingSize -> cAdapterIdleTextSize

  if Buffer.TextLength < cAdapterIdleTextSize then
    Result:= 0
  else
    Result:= cAdapterIdleInterval;
end;
-> TSynedit.OptIdleInterval
```
и вычисленный интервал это задержка для адаптера
   ```
 procedure OnEditorIdle(Sender: TObject); virtual;
    //called after text is changed, and pause passed (OptIdleInterval)
    //fast changes (faster than OptIdleInterval): called only after last change   
```
---
я не уверен, что эта опция вообще на что-то влияет. Парсинг запускается сразу же после изменения текста, как думается. По крайней мере, ChangedAtPos -- который очищает инфраструктуру токенов и диапазонов. Я честно не обращал внимания, откуда вызывается AppendToPos, из OnEditorIdle, или нет.

**Comment by Alexey-T** [comment]
она влияет. По изменению -делается очитстка списков, да. но парсинг и покраска после него- уже делаются из OnEditorIdle, а он дергается после НН мс после правки.

**Comment by Alexey-T** [comment]
для потока этот OnEditorIdle уже надо будет не обрабатывать (сам евент пусть будет в atsynedit).

**Comment by AlekId** [comment]
вообще хорошо бы запускать парсинг сразу, а покраску уже после того, как отработал парсер. Без таймера.

**Comment by Alexey-T** [comment]
с потоком так и надо делать. а без потока- так было чтоб не прерывать постоянно парсинг при наборе текста.

**Comment by AlekId** [comment]
хотя нет, пауза некоторая после ввода, типа 0.5-1.0 секунды не помешала бы

**Comment by Alexey-T** [comment]
Согласен.

**Comment by Alexey-T** [comment]
тут и пригодится этот же OnEditorIdle.

**Comment by AlekId** [comment]
```
procedure TATAdapterEControl.OnEditorIdle(Sender: TObject);
begin
  DoCheckEditorList;
  UpdateData(false, true);
  UpdateEditors(true, true);
end;     
вот этот UpdateEditors похоже и виновник тормозов!
```

**Comment by AlekId** [comment]
вывести его интерфейсом и прокинуть в клиент. Чтобы Finished клиента вызывал
```
if assigned(FiAdapter) then 
  FiAdapter.UpdateEditors(true, true)
```

**Comment by Alexey-T** [comment]
виновник он может быть только если в Куде работает delayed_parsing, т е файл большой.

**Comment by AlekId** [comment]
нет, не думаю. UpdateData вызывает AppendToPos, как я понял, AppendToPos и UpdateEditors таким образом работают одновременно, конкурируя за данные, которые, к тому же были стерты ранее ChangeAtPos.
Два потока мешают друг другу, какой бы ни была задержка

**Comment by AlekId** [comment]
[cudatext.zip](https://github.com/Alexey-T/EControl/files/3119197/cudatext.zip)
вот я всё-таки засунул в нить ChangedAtPos, и прокинул событие UpdateEditors

**Comment by Alexey-T** [comment]
> Немного поправил чтение грамматик -- слишком часто вызывался CompileGrammar, и дергался парсинг.

можно как отдельный пач? Или ждать всего.

**Comment by Alexey-T** [comment]
берем файл
https://github.com/kvichans/cuda_find_in_files/blob/master/cd_fi_in_fi.py
ставим или убираем коммент (решетка) у 1й строки с import. Завис на 1.5сек

**Comment by AlekId** [comment]
кажется, нужно после решетки обязательно сдвинуть каретку ввода, чтобы получить задержку?
у вас это в логе видно, красная строчка?

**Comment by Alexey-T** [comment]
не, я просто печатаю решетку. или просто удаляю ее по BkSp.

**Comment by AlekId** [comment]
у вас лог работает? что там в этот момент?

**Comment by AlekId** [comment]
ладно, в любом случае нужно посмотреть. Тот файл, который я вам отправил, не показывает стек вызовов, так как нужно вместо map было dbg прикреплять

**Comment by AlekId** [comment]
вот тут подозрительно очень
```
procedure TATAdapterEControl.OnEditorCaretMove(Sender: TObject);
begin
  UpdateRangesActive(Sender as TATSynEdit);
end;
```

**Comment by Alexey-T** [comment]
загружусь в Вин10, скажу про лог.

**Comment by Alexey-T** [comment]
UpdateRangesActive(Sender as TATSynEdit); --это для динамич. подсветки ranges (при опции Куды lexer_dynamic_hilite)

**Comment by AlekId** [comment]
[app.zip](https://github.com/Alexey-T/EControl/files/3120778/app.zip)
но нужно как-то это притормозить, иначе он очищает подстветку, тянется к синтаксеру, и попадает на критическую секцию -- виснет.

**Comment by Alexey-T** [comment]
виснет? тогда подожду новую бету.

**Comment by AlekId** [comment]
виснет на 0.5-1.5 сек

**Comment by AlekId** [comment]
вы что, на лине сидите?

**Comment by Alexey-T** [comment]
да, Лин, и Вин10 в виртуалке (там не хочу тестить) и вторая ОС

**Comment by AlekId** [comment]
и если да, запускается ли Лог вьюер под WineHQ?

**Comment by Alexey-T** [comment]
да, но мееедленно, 10-20сек.

**Comment by AlekId** [comment]
я попробую перебазироваться в линь под vmWare. Среду уже построил, но проект не открывал

**Comment by Alexey-T** [comment]
тот тормоз 1.5с был в Вин10...

**Comment by AlekId** [comment]
блин, я собрал проект в лине, питон программа не нашла, решил прописать его в user.json, а оказывается редактор не реагирует на нажатия, кроме backspace.. Думал, может, мой косяк, подменил исполняемый файл оригиналом -- то же самое..

**Comment by AlekId** [comment]
бубунта 18.04 x386 под vnware

**Comment by AlekId** [comment]
оказалось, какой-то баг gtk, насилу нашёл фикс.. Да уж..

**Comment by AlekId** [comment]
[linux-x32-gtk2.zip](https://github.com/Alexey-T/EControl/files/3122392/linux-x32-gtk2.zip)
вот, кажется, уже нормально

**Comment by Alexey-T** [comment]
Бага с Bksp я не видел. Но видел баг gtk где кнопки остаются светиться после ухода мыши

**Comment by Alexey-T** [comment]
user@user-Notebook:~/cudatext_build/_tst$ file cudatext
cudatext: ELF 32-bit LSB executable,

у меня Лин х64.

**Comment by AlekId** [comment]
и что, не запускается что ли?

**Comment by Alexey-T** [comment]
не запускается.

**Comment by AlekId** [comment]
https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit

**Comment by AlekId** [comment]
раз вы линуксоид, то небось разберетесь?

**Comment by Alexey-T** [comment]
32 битного Лина нет.

**Comment by AlekId** [comment]
sudo dpkg --add-architecture i386
sudo apt-get install multiarch-support
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

**Comment by AlekId** [comment]
может 
sudo apt-get install ia32-libs

**Comment by Alexey-T** [comment]
не помогло. те три команды - и так все стояло. последняя не работает. 
ставить Лин х32?

**Comment by AlekId** [comment]
нет..

**Comment by AlekId** [comment]
попробую кросскомпилятор построить

**Comment by Alexey-T** [comment]
для этого - https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases

**Comment by AlekId** [comment]
я его всю дорогу использую. И лазарь построен им, и компилятор -- хоть на выни, хоть на лине.

**Comment by Alexey-T** [comment]
вчера мы с автором (deluxe) приделали cross for Solaris x64.

**Comment by AlekId** [comment]
у меня не выходит. Компилятор строится но линкер ругается на libphread / glibs что-то там не резовится, и фейл. Вероятно crossbinutils несогласованы. Я сейчас ставлю 64-разрядное ядро на линь, может, так получится

**Comment by Alexey-T** [comment]
хм, тогда надо баг репорт в ГХ Делюкса.

**Comment by AlekId** [comment]
[linux-x64-gtk2.zip](https://github.com/Alexey-T/EControl/files/3123439/linux-x64-gtk2.zip)
мне удалось таки настроить кросс-компилятор. Покопался в fpc.cfg, установил пару кроссовых либ, обновил.. 
Короче, оно даже запускается теперь на, в сущности, 32-разрядном лине, куда я впихнул 64-разрядное ядро и несколько "foreign-architecture" библиотек

**Comment by Alexey-T** [comment]
открыл большой Пас файл. раскрасился не весь- на 1м экране не все токены есть.
при ctrl+W - креш
```
Assertion failed (ec_syntanal.pas, line 4127).

Press OK to ignore and risk data corruption.
Press Abort to kill the program.
```

**Comment by Alexey-T** [comment]
[__big1.zip](https://github.com/Alexey-T/EControl/files/3123703/__big1.zip)

**Comment by Alexey-T** [comment]
на том же файле  - пока идет парсинг после правки в начале (он >20c), я еще печатаю в 1м экране- 'ddd' (строчку зеленую), и я ее набрал а все равно 1й экран не покрасился..

при ВНИЗ покрасился- но не весь
![bad](https://user-images.githubusercontent.com/4154978/56847444-ad8bdc80-68e3-11e9-879b-a65f4bc1e10b.png)

**Comment by AlekId** [comment]
[cudatext.zip](https://github.com/Alexey-T/EControl/files/3125427/cudatext.zip)
попробуйте. Я нашел баг, который вызывал креш (он проявляется только на 64-битном компиляторе, хотя существовал всюду. Мне пришлось еще 64-битный gdb воткуть в систему). 

Что касается неполной покраски -- то это происходит потому, что в главном потоке вызывается процедура подстветки, и реквестирует токены -- чтобы не было залипания -- рабочий поток сразу либо "откладывается", либо приостанавливается, и отдаёт, что есть. 
Неполную покраску я воркараундил, теперь AppendToPos отрисовывает по крайней мере 5тыс. символов, прежде чем среагировать на стоп-реквест.
Ну и еще небольшие правки.
[cudatext.zip](https://github.com/Alexey-T/EControl/files/3125461/cudatext.zip)

**Comment by AlekId** [comment]
берите файл, что внизу, он самый новый.

**Comment by Alexey-T** [comment]
Отлично, утром посмотрю

**Comment by Alexey-T** [comment]
Надеюсь это зальёте в гх, вдруг диск полетит

**Comment by Alexey-T** [comment]
ой. взял из Лаз файл ide/main.pp. перед "unit main" печатаю слово -- файл не красится (пока не отпарсится весь -или не нажму Вправо)

**Comment by Alexey-T** [comment]
ой. на последнем экране (тот же main.pp) печатаю- красится через секунду.

**Comment by AlekId** [comment]
у меня было (и есть) подозрение, что работа адаптера ломает процесс парсинга (по крайней мере блоки фолдинга). Поэтому я всюду, где дотянулся, выключил его работу до конца полного парсинга.
Но потом я увидел, что в некоторых случаях (движения каретки ввода, к примеру) адаптер всё же тянется к сырым данным клиента. И чтобы предотвратить подвисания, мне пришлось сделать несколько послаблений на доступ -- те самые YieldData которые вы должны были видеть в логе. 
Короче говоря, сейчас я прокинул событие завершения AppendToPos к адаптеру, и в некотором роде вызываю перекраску. 
Реальная проблема этого парсера -- что паршивые 15тыс строк парсяться аж 4-5 секунд.. Там где-то глупая ошибка. В целом это хорошо --

> Исправлять глупые ошибкы много легче, чем ошибки умных (с) AlekXL

[cudatext.zip](https://github.com/Alexey-T/EControl/files/3126148/cudatext.zip)

**Comment by Alexey-T** [comment]
(может из-за медленности regex: ec_RegExpr написал Захаров, автор EControl)

**Comment by Alexey-T** [comment]
на любом экране (тот же main.pp) печатаю- красится через 1/2 секунду.

теперь нету мелкого progressbar (угол куды) для парсинга.

**Comment by AlekId** [comment]
> на любом экране (тот же main.pp) печатаю- красится через 1/2 секунду.
и это проблема? как я понимаю, changeatpos очищает всё с указанной позиции, и адаптер делает то же.. Подсветка начинается ровно тогда, когда отрабатывает AppendAtPos, через асинхронный вызов в главный поток -- там вызывается Invalidate для окна TSynEdit, и там уж он отрисовывает.

> теперь нету мелкого progressbar (угол куды) для парсинга.
это я исправил. Закоментировал строчку, чтобы не мешалась.
[cudatext.zip](https://github.com/Alexey-T/EControl/files/3126699/cudatext.zip)

**Comment by AlekId** [comment]
> (может из-за медленности regex: ec_RegExpr написал Захаров, автор EControl)
я как раз пытаюсь сообразить, как в лазаре профайлер прикрутить, но это уже за пределами проекта.
что касается регекса... pcre -- надежный и быстрый, что религия запрещает использовать? Зачем это поделие нужно вообще?

**Comment by Alexey-T** [comment]
pcre- в FPC не видел. есть RegExpr. он не умеет lookahead/lookbehind assertion + variable length in assertion text.

**Comment by Alexey-T** [comment]
https://forum.lazarus.freepascal.org/index.php/topic,38983.0.html

**Comment by Alexey-T** [comment]
а можно сделать чтобы очищались не все токены от каретки -а только токены от каретки лежащие **на строке с кареткой**? тогда надо чтоб парсер имел свои токены, а это не ок?

**Comment by AlekId** [comment]
AppendtoPos на этом файле main.pp обычно отрабатывает за 330 мс. Плюс накладные расходы на асинхронный вызов, плюс очередь сообщений для Invalidate -- вот вам и полсекунды

**Comment by AlekId** [comment]
по идее да.. Всё, что не является блочной иструкцией типа begin end, repeat until , можно парсить именно так. Но это за пределами наших договоренностей.

**Comment by AlekId** [comment]
По хорошему, лучше выяснить что тормозит -- может, там 5 сек исправить, и тогда файл будет парситься по мегабайту в секунду.

**Comment by Alexey-T** [comment]
> AppendtoPos на этом файле main.pp обычно отрабатывает за 330 мс. Плюс накладные расходы на асинхронный вызов, плюс очередь сообщений для Invalidate -- вот вам и полсекунды

330 на весь файл? а на текущий экран (от каретки) меньше. тогда при парсинге до нижней строки экрана надо отрисовать.

**Comment by AlekId** [comment]
330 на AppentoPos, который ко конца экрана парсит.

**Comment by AlekId** [comment]
потом DoSyntaxWork работает (IdleAppend в девичестве)

**Comment by Alexey-T** [comment]
> По хорошему, лучше выяснить что тормозит -- может, там 5 сек исправить, и тогда файл будет парситься по мегабайту в секунду.

Как я могу помоч?

**Comment by AlekId** [comment]
и 5 секунд на 13тысяч строк 
https://www.youtube.com/watch?v=lUV9W9ndorw

> Как я могу помоч?
я работаю за деньги. Задачу по вынесению парсинга в поток выполнил. Заплатите, тогда и будет разговор.

**Comment by Alexey-T** [comment]
хочу дать другу на тест. а у него Вин х64. можно cudatext.exe, pls?

**Comment by AlekId** [comment]
[win32.zip](https://github.com/Alexey-T/EControl/files/3126853/win32.zip)
я в основном на винде и писал, так что вряд ли он найдет проблемы, специфичные для Win

**Comment by AlekId** [comment]
под 64 бита я на вин не собирал -- лазарь у меня x32 gdb -64 бит не хочет с ним дружить на в винде (в отл. от линя). Да и не нужно, думается, 64 бита.

**Comment by Alexey-T** [comment]
позову @kvichans в коменты.

**Comment by Alexey-T** [comment]
написал про плату- в личку rubrd.

**Comment by AlekId** [comment]
ага, я ответил

**Comment by kvichans** [comment]
беру, смотрю...

**Comment by AlekId** [comment]
так, небольшая задержка будет, так как я боюсь напортачить. Сейчас адаптер забэкапил в зип, и попробую скоммитить.

**Comment by AlekId** [comment]
я не особо запоминал, где и что менял. Так что если не компилится или поведение не то, что в моих билдах, то пишите.
Да и логгер -- мормот логгер хорош, но  забагован, его я тоже правил. Щас попробую скоммиттить.

**Comment by Alexey-T** [comment]
FBuffer.Lock;
Lock добавлен в atsynedit- нужен пач..

**Comment by kvichans** [comment]
Что за суета? Брать или ждать?

**Comment by Alexey-T** [comment]
@kvichans Бинарник брать- суета про pull req.

**Comment by Alexey-T** [comment]
@kvichans Про замечяния- создайте новый issue, чтобы тут не терялось

**Comment by kvichans** [comment]
Скачал. Внутри
cudatext.exe
LogView.exe
Что с этим делать? Подменить exe в последнем 32-релизе?

**Comment by Alexey-T** [comment]
да, верно.

**Comment by AlekId** [comment]
напрасно вы ассерты выкинули.. Вроде бы их в проекте для package принудительно включить не удастся

**Comment by Alexey-T** [comment]
`-dDEBUG` ? верну их.

**Comment by Alexey-T** [comment]
Может можно методы Lock/Unlock для FBuffer дать хелпером. или жду пач к atsynedit

**Comment by AlekId** [comment]
не только. Еще -Sa 
Assert не делает ничего без этой настройки. 
А что, там не включено? щас посмотрю

**Comment by Alexey-T** [comment]
-Sa не убирал, -dDEBUG вернул...

**Comment by AlekId** [comment]
[atstringproc_textbuffer.zip](https://github.com/Alexey-T/EControl/files/3127226/atstringproc_textbuffer.zip)
вы этот файл вроде не меняли давно, так что может просто замените? К тому же это вроде никгода не работало -- там Assert стоит, но в package не был прописан -Sa

**Comment by Alexey-T** [comment]
у меня -Sa был прописан.

**Comment by Alexey-T** [comment]
все собралось (Лин 64). тогда закроем issue, дам новый при вопросах. Спасибо
