### ISSUE TITLE
Testing new cudatext.exe win32

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/EControl_AlekId#7]
Взял 32-релиз
Подменил exe
Перенес настройки+плагины+тему из рабочего Куд
Открыл 
 CudaText\py\cuda_find_in_files\cd_fi_in_fi.py  145 Kb
Раскраска появилась через несколько минут!

**Comment by Alexey-T** [comment]
@AlekId баг?

**Comment by Alexey-T** [comment]
файл тут- https://github.com/kvichans/cuda_find_in_files

**Comment by kvichans** [comment]
Может быть это моя настройка влияет?:
"lexer_delayed_parsing_size" : 300000,

**Comment by Alexey-T** [comment]
@kvichans не повторил- парсит 2-3 сек.
@AlekId эта настройка еще работает?

**Comment by kvichans** [comment]
Раскраска при перезапуске начинается заново?

**Comment by kvichans** [comment]
Что удалить, чтобы повторить чистый запуск?

**Comment by Alexey-T** [comment]
При открытии вначале- красится сразу , а если открылось в конце файла (по истории) красит через 2сек

**Comment by Alexey-T** [comment]
Чистый запуск- удалить settings/*history*

**Comment by kvichans** [comment]
Удалил history.json, перезпустил Куд
Через СессМана открыл тот же файл
Ждал дольше 5 минуты - раскраска не появилась!

**Comment by kvichans** [comment]
раскраска не появилась (после 10 мин) еще у нескольких файлов
но не у всех - соседний cd_fif_api.py раскрасился

**Comment by Alexey-T** [comment]
Покрасился только фокусированный файл, а пассивные нет? есть группы? можно скрин?

**Comment by kvichans** [comment]
До сих пор нет раскраски
![image](https://user-images.githubusercontent.com/7419630/56896808-7eb56800-6a95-11e9-8369-14832c6a1a9a.png)

**Comment by Alexey-T** [comment]
Так в начале файла строка, зелёная большая

**Comment by kvichans** [comment]
Удалил history.json
Запустил Куд
Отказался устанавливать лексы
Открыл файл py\cuda_find_in_files\cd_fi_in_fi.py. Норм раскраска. Закрыл
Вызывал СессМан команду "недавние сессии" - загрузил 
Получил снимок выше
После закрытия такой лог
[cudatext 20190429 155313.log](https://github.com/Alexey-T/EControl/files/3127446/cudatext.20190429.155313.log)

**Comment by AlekId** [comment]
так какой файл сейчас не красится?

**Comment by Alexey-T** [comment]
Я написал похожий баг но его легко увидеть - соседнее issue. А этот видно только если открывать сессию с к файлами через плагин session manager

**Comment by AlekId** [comment]
cd_fi_in_fi.py у меня нету ..

**Comment by AlekId** [comment]
[win32.zip](https://github.com/Alexey-T/EControl/files/3129690/win32.zip)
попробуйте

**Comment by kvichans** [comment]
Вчера было две проблемы
- Не раскрашивался файл cd_fi_in_fi.py, который становился активным после открытия сессии)
- Креш после открытия сессии, если становился активным файл cuda_differ\__init__.py

Сегодня на одну проблему меньше
- Раскраски cd_fi_in_fi.py нет
- Креша нет

**Comment by kvichans** [comment]
Могу дать все файлы для повторения первой проблемы

**Comment by Alexey-T** [comment]
поправилось от моего пача.
