### ISSUE TITLE
New cudatext, Linux x64

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/EControl_AlekId#8]
опция user.json
"ui_reopen_session": true,

открыл 3 файла в 2 группах

- user.json - группа1, таб1
- cd_fi_in_fi.py из https://github.com/kvichans/cuda_find_in_files - группа1, таб2
- `__init__.py` из py/cuda_addonman- группа2

закрыл куд. открыл куд. криво покрашен файл в группе2. скрин

![Screenshot from 2019-04-29 16-10-17](https://user-images.githubusercontent.com/4154978/56898798-9f33f100-6a9a-11e9-8f6c-504ff81c8946.png)

@AlekId

**Comment by AlekId** [comment]
это что надо сделать, чтобы разделился редактор?

**Comment by Alexey-T** [comment]
Верхнее меню = , сделать 2 группы

**Comment by Alexey-T** [comment]
Похоже едет отрисовка во время Парсинга и что то лочится

**Comment by AlekId** [comment]
может, Kazam -ом запишете, что и как делаете, потому что я даже не знаю, как это воспроизвести.

**Comment by Alexey-T** [comment]
видео- в редакторе вызвать меню = и поставить 2 группы, открыть в них 3 файла.

[Screencast 2019-04-29 16:47:29.zip](https://github.com/Alexey-T/EControl/files/3127641/Screencast.2019-04-29.16.47.29.zip)

**Comment by AlekId** [comment]
хм,. пока я пытался воспроизвести вашу ошибку (на вин), у меня вылетел ассерт на буфер лок.  Может, проблемы связваны? У вас **точно** стоит опция -Ca на пакете ATSynEdit?

**Comment by AlekId** [comment]
-Sa опция я имел в виду.

**Comment by AlekId** [comment]
короче, я пока расследую ассерт, а потом, если проблема не пропадёт, займусь этим кейсом.

**Comment by Alexey-T** [comment]
не стояла, поставил -Sa (как checkbox in dialog). все равно тоже самое.

**Comment by AlekId** [comment]
пока разберусь с ассертом..

**Comment by Alexey-T** [comment]
(ATStringBuffer обновляется из atsynedit_adapter_econtrol, может парсер взял неверное состояние)

**Comment by AlekId** [comment]
да, и проблема может возникнуть, если еще используемое в потоке старое содержимое буфер адаптер попытается подменить новым. В сущности, как раз за этим должен следить клиент. Либо клиент следит неправильно, либо буфер всё-таки портится.

**Comment by Alexey-T** [comment]
Около Buffer.Setup есть проверка

**Comment by Alexey-T** [comment]
Buffer врядли портится- правок то не было- он 1 раз установился и все.

**Comment by Alexey-T** [comment]
поправилось от моего патча!
